import json
import uuid
import datetime
import subprocess
from pathlib import Path
from crewai import Agent, Crew, Task
from crewai.llm import LLM
from crewai_tools import FileReadTool, FileWriterTool
from litellm import file_content

# Local LLM (Ollama)
llm = LLM(
    model="ollama/llama3.1:latest",
    base_url="http://localhost:11434"
    )

def now():
    return datetime.datetime.utcnow().isoformat()

def make_response(sender, recipient, task_type, payload, status="done", error=None):
    return {
        "id": str(uuid.uuid4()),
        "timestamp": now(),
        "sender": sender,
        "recipient": recipient,
        "task_type": task_type,
        "context": "",
        "payload": payload,
        "status": status,
        "error": error
    }

class EngineeringAgent:

    def __init__(self):
        self.name = "ENG"


    file_writer_tool = FileWriterTool()
    file_read_tool = FileReadTool()

    Eng_Agent = Agent(
            role="Engineering Agent",
            goal="Write and maintain high‑quality code based on product specs.",
            backstory="You are the engineering team of a virtual company.",
            llm=llm
    )
    #Code reviewer agent
    Testing_Agent = Agent(
        role="Testing Lead Agent",
        goal="Design tests for testing the code generated by the engineering team.",
        backstory="You are the testing lead of a virtual company, responsible for ensuring the quality of the code produced by the engineering team.",
        llm=llm
    )

    def generate_code(self, spec):
        taskEng = Task( 
            description=f"""
            Write clean, minimal python code for the following requirement:\n\n{spec}\n\n. Return only the code.
            """,
            expected_output="only the code that fulfills the specification, without any explanations or comments.",
            agent=self.Eng_Agent
        )

        crew = Crew(
            agents = [self.Eng_Agent],
            tasks = [taskEng],
            verbose = True
        )        
        inputs = {
            "topic_context": "CrewAI is a framework for building multi-agent systems."
        }
        result = crew.kickoff(inputs=inputs)
        return result
    
    def generate_tests(self, spec):
        taskEng = Task( 
            description=f"""
            Write a series of thorough test for pyhton code written to meet the following requirement:\n\n{spec}\n\n. The code should run in a Python environment. Return only the code.
            """,
            expected_output="only the code that fulfills the specification, without any explanations or comments.",
            agent=self.Testing_Agent
        )

        crew = Crew(
            agents = [self.Testing_Agent],
            tasks = [taskEng],
            verbose = True
        )        
        inputs = {
            "topic_context": "CrewAI is a framework for building multi-agent systems."
        }
        result = crew.kickoff(inputs=inputs)
        return result

    def write_to_repo(self, file_path, content):
        path = Path(file_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        return str(path)

    def handle_message(self, message):
        task_type = message["task_type"]
        payload = message["payload"]

        try:
            print("here")
            if task_type == "generate_code":
                code = self.generate_code(payload["spec"]).raw
                with open(".github\\workflows\\agent_output\\codeFile.py", "w") as file:
                    file.write(code)

                code = self.generate_tests(payload["spec"]).raw
                with open(".github\\workflows\\agent_output\\testFile.py", "w") as file:
                    file.write(code)

                #file_path = payload.get("repo_path", "generated/code.py")
                #saved_path = "none yet"#self.write_to_repo(file_path, code)
                return make_response(
                    sender=self.name,
                    recipient=message["sender"],
                    task_type=task_type,
                    payload={ "code": code}
                )

            else:
                return make_response(
                    sender=self.name,
                    recipient=message["sender"],
                    task_type=task_type,
                    payload={},
                    status="error",
                    error=f"Unknown task_type: {task_type}"
                )

        except Exception as e:
            print(e)
            return make_response(
                sender=self.name,
                recipient=message["sender"],
                task_type=task_type,
                payload={},
                status="error",
                error=str(e)
            )

if __name__ == "__main__":
    import sys
    #raw = sys.stdin.read()
    message = json.loads("""
    {
  "id": "req-002",
  "timestamp": "2026-03-02T16:30:00Z",
  "sender": "PM",
  "recipient": "ENG",
  "task_type": "generate_code",
  "context": {
    "priority": "high",
    "target_release": "2026-04-15"
  },
  "payload": {
    "spec":"Write a calculator in Python that can perform basic arithmetic operations: addition, subtraction, multiplication, and division. The calculator should have a simple command-line interface where users can input expressions like '2 + 3' or '10 / 5' and receive the correct result. Ensure that the calculator handles invalid inputs gracefully and provides informative error messages."
    
  },
  "status": "pending",
  "error": ""
}
""")
    agent = EngineeringAgent()
    response = agent.handle_message(message)
    print(json.dumps(response, indent=2))
